name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.16.0
        with:
          java-version: 21      

      - name: Maven Cache löschen
        run: mvn dependency:purge-local-repository
      
      - name: Build
        run: mvn clean package
      
      - name: Test
        run: mvn test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/*.jar
          retention-days: 90
