name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.16.0
        with:
          java-version: 21
      - name: Build
        run:  mvn clean compile assembly:single
      - name: Test
        run: mvn test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: target
          retention-days: 90
